substitutions:
  hostname: bathroom-lights
  friendly_name: Bathroom Lights
  light_name: Bathroom

packages:
  device_base: !include devices/sonoff-sv-light.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    id: button
    internal: true
    on_press:
      then:
        - light.toggle: device_light
