substitutions:
  hostname: bedroom-lights
  friendly_name: Bedroom Lights
  light_name: Bedroom

packages:
  device_base: !include devices/sonoff-sv-light.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    id: button
    internal: true
    on_click:
      then:
        - light.toggle: device_light
    on_double_click:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.office
