substitutions:
  node_platform: ESP8266
  node_board: esp01_1m

packages:
  device_base: !include ../common/base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: ${friendly_name} Button
    id: button
    on_press:
      - switch.toggle: device_switch

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    update_interval: 1s
    current:
      name: ${friendly_name} Current
      id: current

    voltage:
      name: ${friendly_name} Voltage
      id: voltage

    power:
      name: ${friendly_name} Power
      id: power

switch:
  - platform: gpio
    name: ${friendly_name}
    pin: GPIO12
    id: device_switch

status_led:
  pin: GPIO13
