packages:
  wifi: !include ../common/wifi.yaml
  device_base: !include ../common/base.yaml

esphome:
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: status
    name: "${friendly_name} Lights Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: binary
    name: "${friendly_name}"
    output: relay
    id: ${device_name}
