substitutions:
  node_platform: ESP8266
  node_board: esp01_1m

packages:
  device_base: !include ../common/base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml

output:
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: binary
    name: ${light_name}
    output: relay
    id: device_light
