esphome:
  name: "${device_name}"
  build_path: "./build/${device_name}"

logger:
  level: DEBUG

api:

ota:

# web_server:
#   port: 80

sensor:
  - platform: wifi_signal
    name: WiFi Signal Strength
    id: "${device_name}_wifi_signal"
    update_interval: 15s
  - platform: uptime
    name: Uptime
    id: "${device_name}_uptime"

text_sensor:
  - platform: version
    name: "ESPHome Version"
    id: "${device_name}_esphome_version"
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: "${device_name}_ip_address"
    ssid:
      name: SSID
      id: "${device_name}_ssid"
    bssid:
      name: BSSID
      id: "${device_name}_bssid"
    mac_address:
      name: MAC Address
      id: "${device_name}_mac_address"
