binary_sensor:
  - platform: status
    name: ${friendly_name} Status
    id: device_status

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal Strength
    id: device_wifi_signal
    update_interval: 15s

  - platform: uptime
    name: ${friendly_name} Uptime
    id: device_uptime
    update_interval: 15s

text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version
    id: esphome_version

  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      id: ip_address

    ssid:
      name: ${friendly_name} SSID
      id: ssid

    bssid:
      name: ${friendly_name} BSSID
      id: bssid

    mac_address:
      name: ${friendly_name} MAC Address
      id: mac_address

switch:
  - platform: restart
    name: ${friendly_name} Restart
    id: device_restart
